#!/bin/sh
set -e
set -x
xcrun --sdk macosx clang -O -arch x86_64 -DSQLITE_DEFAULT_FOREIGN_KEYS=1 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_RTREE -DSQLITE_OS_UNIX ../sqlite3/sqlite3.c ../sqlite3/shell.c
